/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * System health check
         * @description 回傳各元件健康狀態，部分元件不可用時回傳 degraded。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK（含降級狀態） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/integrity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * DB/Cache consistency and observability check
         * @description EJ 每日巡視用。比對 DB 與 Redis 快取，回傳 Observability 指標。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK（含降級狀態） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IntegrityResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/symbols": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get list of stock symbols
         * @description 回傳系統動態管理的股票清單，每日從 FinMind 同步。
         */
        get: {
            parameters: {
                query?: {
                    /** @description 交易所篩選 */
                    exchange?: "TWSE" | "TPEX";
                    /** @description 是否只回傳上市中的標的，預設 true */
                    is_active?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SymbolsResponse"];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candles/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get candlestick data with optional indicators
         * @description 單次請求最多回傳 2000 根 K 線。
         *     超過範圍回傳 400 QUERY_RANGE_TOO_LARGE。
         *     使用 next_cursor 分頁取得後續資料。
         */
        get: {
            parameters: {
                query: {
                    /** @description 開始時間戳（毫秒） */
                    from_ms: number;
                    /** @description 結束時間戳（毫秒） */
                    to_ms: number;
                    /** @description K 線時間粒度，預設 1h */
                    interval?: "1m" | "5m" | "15m" | "1h" | "4h" | "1d";
                    /** @description 逗號分隔的指標名稱，如 "ma20,rsi,macd" */
                    indicators?: string;
                    /** @description 分頁游標，由上一頁 response 的 next_cursor 提供 */
                    cursor?: string;
                };
                header?: never;
                path: {
                    /** @description 股票代號，如 "2330" */
                    symbol: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CandlesResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                /** @description Symbol not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/indicators/compute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compute technical indicators dynamically
         * @description 支援動態參數化指標請求。
         *     計算順序由 Rust IndicatorFactory 依 DAG 拓撲排序自動決定。
         *     回應包含 dag_execution_order 供驗證。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ComputeIndicatorsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ComputeIndicatorsResponse"];
                    };
                };
                /** @description Bad Request（含 INVALID_INDICATOR_CONFIG） */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                /** @description Computation overflow */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Indicator compute failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/signals/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get trading signals
         * @description AI 服務正常時回傳 source=ai_ensemble。
         *     AI 超時或不可用時自動降級，回傳 source=technical_only，
         *     fallback_reason 標注原因。
         */
        get: {
            parameters: {
                query: {
                    from_ms: number;
                    to_ms: number;
                };
                header?: never;
                path: {
                    symbol: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SignalsResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                /** @description Symbol not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description AI service timeout（已自動降級） */
                504: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get AI model prediction
         * @description Rust Gateway 轉發至 Python AI Service。
         *     Python 端保證 up_probability + down_probability == 1.0。
         *     所有數值 is_finite() == true。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PredictionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PredictionResponse"];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                /** @description AI service unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description AI service timeout */
                504: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backtest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run backtest
         * @description 回測引擎透過 POST /api/v1/indicators/compute 取得 Rust 指標，
         *     確保與實盤計算結果一致。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BacktestRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BacktestResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: "ok" | "degraded";
            /** Format: int64 */
            timestamp_ms: number;
            components: {
                /** @enum {string} */
                database: "ok" | "unavailable";
                /** @enum {string} */
                redis: "ok" | "unavailable";
                /** @enum {string} */
                python_ai_service: "ok" | "unavailable";
            };
            version: string;
        };
        IntegrityResponse: {
            /** @enum {string} */
            status: "ok" | "degraded" | "error";
            /** Format: int64 */
            timestamp_ms: number;
            checks: {
                cache_db_consistency: {
                    /** @enum {string} */
                    status: "ok" | "mismatch";
                    sample_size: number;
                    max_deviation_pct: number;
                    note?: string | null;
                };
                indicator_dag_order: {
                    /** @enum {string} */
                    status: "ok" | "error";
                    /** Format: int64 */
                    last_execution_ms?: number;
                };
                python_ai_service: {
                    /** @enum {string} */
                    status: "ok" | "unavailable";
                    last_response_ms?: number;
                };
                data_source: {
                    /** @enum {string} */
                    primary: "finmind" | "yfinance";
                    /** @enum {string} */
                    status: "ok" | "rate_limited";
                    fallback?: string | null;
                    rate_limit_remaining_pct: number;
                };
            };
            observability: {
                /** @description 最新 K 線時間與當前時間差值（秒），告警閾值 300 */
                data_latency_seconds: number;
                /** @enum {string} */
                data_latency_status: "ok" | "warning" | "critical";
                /** @description AI 推論 P99 耗時（毫秒），告警閾值 200 */
                ai_inference_p99_ms: number;
                /** @enum {string} */
                ai_inference_status: "ok" | "warning" | "critical";
                /** @description 最近 1 小時 API 成功率，告警閾值 99% */
                api_success_rate_pct: number;
                /** @enum {string} */
                api_success_rate_status: "ok" | "warning" | "critical";
                /** @description 最近 1 小時 BridgeError 發生次數，告警閾值 5 */
                bridge_errors_last_hour: number;
            };
        };
        SymbolsResponse: {
            symbols: components["schemas"]["Symbol"][];
            count: number;
            /** Format: int64 */
            last_synced_ms: number;
        };
        Symbol: {
            /** @example 2330 */
            symbol: string;
            /** @example 台積電 */
            name: string;
            /** @enum {string} */
            exchange: "TWSE" | "TPEX";
            /** @enum {string} */
            data_source: "finmind" | "yfinance";
            /** Format: int64 */
            earliest_available_ms: number;
            /** Format: int64 */
            latest_available_ms: number;
            is_active: boolean;
            /** Format: int64 */
            updated_at_ms: number;
        };
        CandlesResponse: {
            symbol: string;
            /** @enum {string} */
            interval: "1m" | "5m" | "15m" | "1h" | "4h" | "1d";
            /** Format: int64 */
            from_ms: number;
            /** Format: int64 */
            to_ms: number;
            candles: components["schemas"]["CandleItem"][];
            /** @description 本次回傳的 K 線數量 */
            count: number;
            /** @description 符合條件的總 K 線數量 */
            total_available: number;
            /** @description 分頁游標，null 表示已取完 */
            next_cursor?: string | null;
            /** @enum {string} */
            source: "database" | "cache";
            cached: boolean;
            /** Format: int64 */
            computed_at_ms: number;
        };
        CandleItem: {
            /** Format: int64 */
            timestamp_ms: number;
            /** Format: double */
            open: number;
            /** Format: double */
            high: number;
            /** Format: double */
            low: number;
            /** Format: double */
            close: number;
            /** Format: int64 */
            volume: number;
            /** @description 動態指標結果，key 為指標名稱（如 ma20、rsi14、macd） */
            indicators?: {
                [key: string]: unknown;
            };
        };
        ComputeIndicatorsRequest: {
            /** @description 冪等性識別碼，格式建議 "req-YYYYMMDD-NNN" */
            request_id: string;
            symbol: string;
            /** Format: int64 */
            from_ms: number;
            /** Format: int64 */
            to_ms: number;
            /** @enum {string} */
            interval: "1m" | "5m" | "15m" | "1h" | "4h" | "1d";
            /**
             * @description 指標參數，支援兩種格式：
             *     - 參數列表型：{ "ma": [5, 20, 50], "rsi": [14] }
             *     - 具名參數型：{ "bollinger": { "period": 20, "std_dev_multiplier": 2.0 } }
             */
            indicators: {
                [key: string]: unknown;
            };
        };
        ComputeIndicatorsResponse: {
            symbol: string;
            interval: string;
            /** Format: int64 */
            from_ms: number;
            /** Format: int64 */
            to_ms: number;
            /** @description key 為指標名稱，value 為時間序列陣列（如 [150.0, 150.1]） */
            indicators: {
                [key: string]: unknown;
            };
            /** Format: int64 */
            computed_at_ms: number;
            computation_time_ms: number;
            cached: boolean;
            /** @description 指標實際計算順序，供驗證 DAG 拓撲排序結果 */
            dag_execution_order: string[];
        };
        SignalsResponse: {
            symbol: string;
            /** Format: int64 */
            from_ms: number;
            /** Format: int64 */
            to_ms: number;
            signals: components["schemas"]["Signal"][];
            count: number;
        };
        Signal: {
            id: string;
            /** Format: int64 */
            timestamp_ms: number;
            /** @enum {string} */
            signal_type: "BUY" | "SELL";
            /** Format: double */
            confidence: number;
            /** Format: double */
            entry_price: number;
            /** Format: double */
            target_price: number;
            /** Format: double */
            stop_loss: number;
            reason: string;
            /** @enum {string} */
            source: "ai_ensemble" | "technical_only" | "manual_override";
            /** @enum {string} */
            reliability: "high" | "medium" | "low" | "unknown";
            /** @description AI 降級時的原因，如 "AI_SERVICE_TIMEOUT" */
            fallback_reason?: string | null;
        };
        PredictionRequest: {
            request_id: string;
            symbol: string;
            /** @description 指標名稱與數值的 key-value，如 { "ma20": 150.5, "rsi": 55.2 } */
            indicators: {
                [key: string]: number;
            };
            lookback_hours: number;
        };
        PredictionResponse: {
            symbol: string;
            /** Format: double */
            up_probability: number;
            /** Format: double */
            down_probability: number;
            /** Format: double */
            confidence_score: number;
            model_version: string;
            inference_time_ms: number;
            /** Format: int64 */
            computed_at_ms: number;
        };
        BacktestRequest: {
            request_id: string;
            symbol: string;
            strategy_name: string;
            /** Format: int64 */
            from_ms: number;
            /** Format: int64 */
            to_ms: number;
            /** Format: double */
            initial_capital: number;
            /** Format: double */
            position_size_percent: number;
        };
        BacktestResponse: {
            backtest_id: string;
            symbol: string;
            strategy_name: string;
            /** Format: int64 */
            from_ms: number;
            /** Format: int64 */
            to_ms: number;
            /** Format: double */
            initial_capital: number;
            /** Format: double */
            final_capital: number;
            metrics: components["schemas"]["BacktestMetrics"];
            /** Format: int64 */
            created_at_ms: number;
        };
        BacktestMetrics: {
            total_trades: number;
            winning_trades: number;
            losing_trades: number;
            /** Format: double */
            win_rate: number;
            /** Format: double */
            profit_factor: number;
            /** Format: double */
            max_drawdown: number;
            /** Format: double */
            sharpe_ratio: number;
            /** Format: double */
            annual_return: number;
        };
        ErrorResponse: {
            /** @enum {string} */
            error_code: "UNAUTHORIZED" | "AI_SERVICE_TIMEOUT" | "AI_SERVICE_UNAVAILABLE" | "DATA_SOURCE_INTERRUPTED" | "DATA_SOURCE_RATE_LIMITED" | "INDICATOR_COMPUTE_FAILED" | "CACHE_MISS_FALLBACK" | "COMPUTATION_OVERFLOW" | "INVALID_INDICATOR_CONFIG" | "SYMBOL_NOT_FOUND" | "QUERY_RANGE_TOO_LARGE";
            message: string;
            fallback_available: boolean;
            /** Format: int64 */
            timestamp_ms: number;
            request_id?: string | null;
        };
    };
    responses: {
        /** @description X-API-KEY 缺少或無效 */
        UnauthorizedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
